env: development
private_key: jwt-private-key-sizenasional
token_ttl: "86400000"
database:
  #connection to postgresql
  host: prokerin-postgresql
  port: 5432
  db: prokerin-db
  username: postgres
  password: postgres
